usr/bin/oracle
usr/bin/bin2pass
usr/bin/sphinx
usr/bin/websphinx
configs/config etc/sphinx
configs/firefox/websphinx.json usr/share/mozilla/native-messaging-hosts
configs/chrome/websphinx.json etc/chromium/native-messaging-hosts
usr/lib/python*/dist-packages/pwdsphinx-*.egg-info/PKG-INFO
usr/lib/python*/dist-packages/pwdsphinx-*.egg-info/dependency_links.txt
usr/lib/python*/dist-packages/pwdsphinx-*.egg-info/entry_points.txt
usr/lib/python*/dist-packages/pwdsphinx-*.egg-info/requires.txt
usr/lib/python*/dist-packages/pwdsphinx-*.egg-info/top_level.txt
usr/lib/python*/dist-packages/pwdsphinx/__init__.py
usr/lib/python*/dist-packages/pwdsphinx/__pycache__/__init__.cpython-*.pyc
usr/lib/python*/dist-packages/pwdsphinx/__pycache__/sphinxlib.cpython-*.pyc
usr/lib/python*/dist-packages/pwdsphinx/__pycache__/bin2pass.cpython-*.pyc
usr/lib/python*/dist-packages/pwdsphinx/__pycache__/config.cpython-*.pyc
usr/lib/python*/dist-packages/pwdsphinx/__pycache__/oracle.cpython-*.pyc
usr/lib/python*/dist-packages/pwdsphinx/__pycache__/sphinx.cpython-*.pyc
usr/lib/python*/dist-packages/pwdsphinx/__pycache__/websphinx.cpython-*.pyc
usr/lib/python*/dist-packages/pwdsphinx/bin2pass.py
usr/lib/python*/dist-packages/pwdsphinx/config.py
usr/lib/python*/dist-packages/pwdsphinx/oracle.py
usr/lib/python*/dist-packages/pwdsphinx/sphinx.py
usr/lib/python*/dist-packages/pwdsphinx/sphinxlib.py
usr/lib/python*/dist-packages/pwdsphinx/websphinx.py
