name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Used to host cibuildwheel
      - uses: actions/setup-python@v4

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.17.0

      - name: Install libsodium-dev
        run: sudo apt update && sudo apt install libsodium-dev
      
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        env:
           CIBW_SKIP: cp36-*
#          CIBW_BEFORE_BUILD_LINUX: apt update && apt install libsodium-dev
#          CIBW_BEFORE_BUILD_MACOS: brew install libsodium
#          CIBW_BEFORE_BUILD_WINDOWS: 

#     - uses: actions/upload-artifact@v4
#       with:
#         name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
#         path: ./wheelhouse/*.whl
